config/routes.rb
Lobsters::Application.routes.draw do
  scope :format => "html" do
    root :to => "home#index",
      :protocol => (Rails.application.config.force_ssl ? "https://" : "http://"),
      :as => "root"

    get "/404" => "home#four_oh_four", :via => :all

    get "/rss" => "home#index", :format => "rss"
    get "/hottest" => "home#index", :format => "json"

    get "/page/:page" => "home#index"

    get "/newest" => "home#newest", :format => /html|json|rss/
    get "/newest/page/:page" => "home#newest"
    get "/newest/:user" => "home#newest_by_user", :format => /html|json|rss/
    get "/newest/:user/page/:page" => "home#newest_by_user"
    get "/recent" => "home#recent"
    get "/recent/page/:page" => "home#recent"
    get "/hidden" => "home#hidden"
    get "/hidden/page/:page" => "home#hidden"
    get "/saved" => "home#saved", :format => /html|rss|json/
    get "/saved/page/:page" => "home#saved"

    get "/upvoted(.format)" => "home#upvoted"
    get "/upvoted/page/:page" => "home#upvoted"

    get "/top" => "home#top"
    get "/top/page/:page" => "home#top"
    get "/top/:length" => "home#top"
    get "/top/:length/page/:page" => "home#top"

    get "/threads" => "comments#threads"
    get "/threads/:user" => "comments#threads"

    get "/login" => "login#index"
    post "/login" => "login#login"
    post "/logout" => "login#logout"
    get "/login/2fa" => "login#twofa"
    post "/login/2fa_verify" => "login#twofa_verify", :as => "twofa_login"

    get "/signup" => "signup#index"
    post "/signup" => "signup#signup"
    get "/signup/invite" => "signup#invite"

    get "/login/forgot_password" => "login#forgot_password",
      :as => "forgot_password"
    post "/login/reset_password" => "login#reset_password",
      :as => "reset_password"
    match "/login/set_new_password" => "login#set_new_password",
      :as => "set_new_password", :via => [:get, :post]

    get "/t/:tag" => "home#tagged", :as => "tag", :format => /html|rss|json/
    get "/t/:tag/page/:page" => "home#tagged"

    get "/search" => "search#index"
    get "/search/:q" => "search#index"

    resources :stories do
      post "upvote"
      post "downvote"
      post "unvote"
      post "undelete"
      post "hide"
      post "unhide"
      post "save"
      post "unsave"
      get "suggest"
      post "suggest", :action => "submit_suggestions"
    end
    post "/stories/fetch_url_attributes", :format => "json"
    post "/stories/preview" => "stories#preview"
    post "/stories/check_url_dupe" => "stories#check_url_dupe"

    resources :comments do
      member do
        get "reply"
        post "upvote"
        post "downvote"
        post "unvote"

        post "delete"
        post "undelete"

        post "dragon"
        post "undragon"
      end
    end
    get "/comments/page/:page" => "comments#index"
    get "/comments" => "comments#index", :format => /html|rss/

    get "/messages/sent" => "messages#sent", :format => /html|json/
    get "/messages" => "messages#index", :format => /html|json/
    post "/messages/batch_delete" => "messages#batch_delete",
      :as => "batch_delete_messages"
    resources :messages do
      post "keep_as_new"
    end

    get "/c/:id" => "comments#redirect_from_short_id"
    get "/c/:id.json" => "comments#show_short_id", :format => "json"

    # deprecated
    get "/s/:story_id/:title/comments/:id" => "comments#redirect_from_short_id"

    get "/s/:id/(:title)" => "stories#show", :format => /html|json/

    get "/u" => "users#tree"
    get "/u/:username" => "users#show", :as => "user", :format => /html|json/

    get "/avatars/:username_size.png" => "avatars#show"
    post "/avatars/expire" => "avatars#expire"

    post "/users/:username/ban" => "users#ban", :as => "user_ban"
    post "/users/:username/unban" => "users#unban", :as => "user_unban"
    post "/users/:username/disable_invitation" => "users#disable_invitation", :as => "user_disable_invite"
    post "/users/:username/enable_invitation" => "users#enable_invitation", :as => "user_enable_invite"

    get "/settings" => "settings#index"
    post "/settings" => "settings#update"
    post "/settings/delete_account" => "settings#delete_account",
      :as => "delete_account"
    get "/settings/2fa" => "settings#twofa", :as => "twofa"
    post "/settings/2fa_auth" => "settings#twofa_auth", :as => "twofa_auth"
    get "/settings/2fa_enroll" => "settings#twofa_enroll",
      :as => "twofa_enroll"
    get "/settings/2fa_verify" => "settings#twofa_verify",
      :as => "twofa_verify"
    post "/settings/2fa_update" => "settings#twofa_update",
      :as => "twofa_update"

    post "/settings/pushover_auth" => "settings#pushover_auth"
    get "/settings/pushover_callback" => "settings#pushover_callback"
    get "/settings/github_auth" => "settings#github_auth"
    get "/settings/github_callback" => "settings#github_callback"
    post "/settings/github_disconnect" => "settings#github_disconnect"
    get "/settings/twitter_auth" => "settings#twitter_auth"
    get "/settings/twitter_callback" => "settings#twitter_callback"
    post "/settings/twitter_disconnect" => "settings#twitter_disconnect"

    get "/filters" => "filters#index"
    post "/filters" => "filters#update"

    get "/tags" => "tags#index"
    get "/tags.json" => "tags#index", :format => "json"

    post "/invitations" => "invitations#create"
    get "/invitations" => "invitations#index"
    get "/invitations/request" => "invitations#build"
    post "/invitations/create_by_request" => "invitations#create_by_request",
      :as => "create_invitation_by_request"
    get "/invitations/confirm/:code" => "invitations#confirm_email"
    post "/invitations/send_for_request" => "invitations#send_for_request",
      :as => "send_invitation_for_request"
    get "/invitations/:invitation_code" => "signup#invited"
    post "/invitations/delete_request" => "invitations#delete_request",
      :as => "delete_invitation_request"

    get "/hats" => "hats#index"
    get "/hats/build_request" => "hats#build_request",
      :as => "request_hat"
    post "/hats/create_request" => "hats#create_request",
      :as => "create_hat_request"
    get "/hats/requests" => "hats#requests_index"
    post "/hats/approve_request/:id" => "hats#approve_request",
      :as => "approve_hat_request"
    post "/hats/reject_request/:id" => "hats#reject_request",
      :as => "reject_hat_request"

    get "/moderations" => "moderations#index"
    get "/moderations/page/:page" => "moderations#index"
    get "/moderators" => "users#tree", :moderators => true

    get "/privacy" => "home#privacy"
    get "/about" => "home#about"
    get "/chat" => "home#chat"
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :require_logged_in_user

  TOTP_SESSION_TIMEOUT = (60 * 15)

  def index
    @title = "Account Settings"

    @edit_user = @user.dup
  end

  def delete_account
    if @user.try(:authenticate, params[:user][:password].to_s)
      @user.delete!
      if params[:disown].present?
        @user.disown_comments!
      end
      reset_session
      flash[:success] = "Your account has been deleted."
      return redirect_to "/"
    end

    flash[:error] = "Your password could not be verified."
    return redirect_to settings_path
  end

  def update
    @edit_user = @user.clone

    if params[:user][:password].empty? ||
    @user.authenticate(params[:current_password].to_s)
      if @edit_user.update_attributes(user_params)
        flash.now[:success] = "Successfully updated settings."
        @user = @edit_user
      end
    else
      flash[:error] = "Your current password was not entered correctly."
    end

    render :action => "index"
  end

  def twofa
    @title = "Two-Factor Authentication"
  end

  def twofa_auth
    if @user.authenticate(params[:user][:password].to_s)
      session[:last_authed] = Time.now.to_i
      session.delete(:totp_secret)

      if @user.has_2fa?
        @user.disable_2fa!
        flash[:success] = "Two-Factor Authentication has been disabled."
        return redirect_to "/settings"
      else
        return redirect_to twofa_enroll_url
      end
    else
      flash[:error] = "Your password was not correct."
      return redirect_to twofa_url
    end
  end

  def twofa_enroll
    @title = "Two-Factor Authentication"

    if (Time.now.to_i - session[:last_authed].to_i) > TOTP_SESSION_TIMEOUT
      flash[:error] = "Your enrollment period timed out."
      return redirect_to twofa_url
    end

    if !session[:totp_secret]
      session[:totp_secret] = ROTP::Base32.random_base32
    end

    totp = ROTP::TOTP.new(session[:totp_secret],
      :issuer => Rails.application.name)
    totp_url = totp.provisioning_uri(@user.email)

    # no option for inline svg, so just strip off leading <?xml> tag
    qrcode = RQRCode::QRCode.new(totp_url)
    qr = qrcode.as_svg(:offset => 0, color: "000", :module_size => 5,
      :shape_rendering => "crispEdges").gsub(/^<\?xml.*>/, "")

    @qr_svg = "<a href=\"#{totp_url}\">#{qr}</a>"
  end

  def twofa_verify
    @title = "Two-Factor Authentication"

    if ((Time.now.to_i - session[:last_authed].to_i) > TOTP_SESSION_TIMEOUT) ||
    !session[:totp_secret]
      flash[:error] = "Your enrollment period timed out."
      return redirect_to twofa_url
    end
  end

  def twofa_update
    if ((Time.now.to_i - session[:last_authed].to_i) > TOTP_SESSION_TIMEOUT) ||
    !session[:totp_secret]
      flash[:error] = "Your enrollment period timed out."
      return redirect_to twofa_url
    end

    @user.totp_secret = session[:totp_secret]
    if @user.authenticate_totp(params[:totp_code])
      # re-roll, just in case
      @user.session_token = nil
      @user.save!

      session[:u] = @user.session_token

      flash[:success] = "Two-Factor Authentication has been enabled on " <<
        "your account."
      session.delete(:totp_secret)
      return redirect_to "/settings"
    else
      flash[:error] = "Your TOTP code was invalid, please verify the " <<
        "current code in your TOTP application."
      return redirect_to twofa_verify_url
    end
  end

  # external services

  def pushover_auth
    if !Pushover.SUBSCRIPTION_CODE
      flash[:error] = "This site is not configured for Pushover"
      return redirect_to "/settings"
    end

    session[:pushover_rand] = SecureRandom.hex

    return redirect_to Pushover.subscription_url({
      :success => "#{Rails.application.root_url}settings/pushover_callback?" <<
        "rand=#{session[:pushover_rand]}",
      :failure => "#{Rails.application.root_url}settings/",
    })
  end

  def pushover_callback
    if !session[:pushover_rand].to_s.present?
      flash[:error] = "No random token present in session"
      return redirect_to "/settings"
    end

    if !params[:rand].to_s.present?
      flash[:error] = "No random token present in URL"
      return redirect_to "/settings"
    end

    if params[:rand].to_s != session[:pushover_rand].to_s
      raise "rand param #{params[:rand].inspect} != " <<
        session[:pushover_rand].inspect
    end

    @user.pushover_user_key = params[:pushover_user_key].to_s
    @user.save!

    if @user.pushover_user_key.present?
      flash[:success] = "Your account is now setup for Pushover notifications."
    else
      flash[:success] = "Your account is no longer setup for Pushover " <<
        "notifications."
    end

    return redirect_to "/settings"
  end

  def github_auth
    session[:github_state] = SecureRandom.hex
    return redirect_to Github.oauth_auth_url(session[:github_state])
  end

  def github_callback
    if !session[:github_state].present? || !params[:code].present? ||
    (params[:state].to_s != session[:github_state].to_s)
      flash[:error] = "Invalid OAuth state"
      return redirect_to "/settings"
    end

    session.delete(:github_state)

    tok, username = Github.token_and_user_from_code(params[:code])
    if tok.present? && username.present?
      @user.github_oauth_token = tok
      @user.github_username = username
      @user.save!
      flash[:success] = "Your account has been linked to GitHub user " <<
        "#{username}."
    else
      return github_disconnect
    end

    return redirect_to "/settings"
  end

  def github_disconnect
    @user.github_oauth_token = nil
    @user.github_username = nil
    @user.save!
    flash[:success] = "Your GitHub association has been removed."
    return redirect_to "/settings"
  end

  def twitter_auth
    session[:twitter_state] = SecureRandom.hex
    return redirect_to Twitter.oauth_auth_url(session[:twitter_state])
  end

  def twitter_callback
    if !session[:twitter_state].present? ||
    (params[:state].to_s != session[:twitter_state].to_s)
      flash[:error] = "Invalid OAuth state"
      return redirect_to "/settings"
    end

    session.delete(:twitter_state)

    tok, sec, username = Twitter.token_secret_and_user_from_token_and_verifier(
      params[:oauth_token], params[:oauth_verifier])
    if tok.present? && username.present?
      @user.twitter_oauth_token = tok
      @user.twitter_oauth_token_secret = sec
      @user.twitter_username = username
      @user.save!
      flash[:success] = "Your account has been linked to Twitter user @" <<
        "#{username}."
    else
      return twitter_disconnect
    end

    return redirect_to "/settings"
  end

  def twitter_disconnect
    @user.twitter_oauth_token = nil
    @user.twitter_username = nil
    @user.twitter_oauth_token_secret = nil
    @user.save!
    flash[:success] = "Your Twitter association has been removed."
    return redirect_to "/settings"
  end

private

  def user_params
    params.require(:user).permit(
      :username, :email, :password, :password_confirmation, :about,
      :email_replies, :email_messages, :email_mentions,
      :pushover_replies, :pushover_messages, :pushover_mentions,
      :mailing_list_mode, :show_avatars, :show_story_previews,
      :show_submitted_story_threads
    )
  end
end

app/views/settings/index.html.erb
<div class="box wide">
  <div class="legend right">
    <a href="/filters">Filtered Tags</a>
    |
    <%= link_to "Logout", { :controller => "login", :action => "logout" },
      :data => { :confirm => "Are you sure you want to logout?" },
      :method => "post" %>
  </div>
  <div class="legend">
    Account Settings (<a href="/u/<%= @user.username %>">View Profile</a>)
  </div>

  <%= form_for @edit_user, :url => settings_path, :method => :post,
  :html => { :id => "edit_user" } do |f| %>
    <%= error_messages_for f.object %>

    <div class="boxline">
      <%= f.label :username, "Username:", :class => "required" %>
      <%= f.text_field :username, :size => 15 %>
      <span class="hint">
        <tt><%= User.username_regex_s %></tt>
      </span>
    </div>

    <div class="boxline">
      <%= label_tag :current_password, "Current Password:",
        :class => "required" %>
      <%= password_field_tag :current_password, nil, :size => 40 %>
    </div>

    <div class="boxline">
      <%= f.label :password, "New Password:", :class => "required" %>
      <%= f.password_field :password, :size => 40, :autocomplete => "off" %>
    </div>

    <div class="boxline">
      <%= f.label :password_confirmation, "Confirm Password:",
        :class => "required" %>
      <%= f.password_field :password_confirmation, :size => 40,
        :autocomplete => "off" %>
    </div>

    <div class="boxline">
      <%= f.label :email, "E-mail Address:", :class => "required" %>
      <%= f.email_field :email, :size => 40 %>
    </div>

    <div class="boxline">
      <%= f.label :about, "About:", :class => "required" %>
      <%= f.text_area :about, :size => "100x5", :style => "width: 600px;" %>
    </div>

    <div class="box">
      <div class="boxline markdown_help_toggler" style="margin-left: 9em;
      width: 600px;">
        <div class="markdown_help_label">
          Markdown formatting available
        </div>

        <div style="clear: both;"></div>

        <%= render :partial => "global/markdownhelp" %>
      </div>
    </div>

    <p>
    <%= f.submit "Save Account Settings" %>
    </p>

    <br>

    <div class="legend">
      External Accounts
    </div>

    <div class="boxline">
      <%= label_tag :gravatar,
        raw("<a href=\"https://gravatar.com/\">Gravatar</a>:"),
        :class => "required" %>
      <span>
        Your avatar will be cached from the Gravatar icon for your e-mail
        address above.
        (<%= link_to "Expire cache", "/avatars/expire", :method => :post %>)
      </span>
    </div>

    <% if Pushover.enabled? %>
      <div class="boxline">
        <%= label_tag :pushover_user_key,
          raw("<a href=\"https://pushover.net/\">Pushover</a>:"),
          :class => "required" %>
        <span>
        <%= link_to((@edit_user.pushover_user_key.present??
          "Manage Pushover Subscription" : "Subscribe With Pushover"),
          "/settings/pushover_auth", :class => "pushover_button",
          :method => :post) %>
        <span class="hint">
          For optional comment and message notifications below
        </span>
        </span>
      </div>
    <% end %>

    <% if Github.enabled? %>
      <div class="boxline">
        <span>
        <%= label_tag :github_username,
          raw("<a href=\"https://github.com/\">GitHub</a>:"),
          :class => "required" %>
        <% if @edit_user.github_username.present? %>
          Linked to
          <strong><a href="https://github.com/<%= h(@edit_user.github_username)
            %>"><%= h(@edit_user.github_username) %></a></strong>
            (<%= link_to "Disconnect", "/settings/github_disconnect",
              :method => :post %>)
        <% else %>
          <a href="/settings/github_auth">Connect</a>
        <% end %>
        </span>
      </div>
    <% end %>

    <% if Twitter.enabled? %>
      <div class="boxline">
        <%= label_tag :twitter_username,
          raw("<a href=\"https://twitter.com/\">Twitter</a>:"),
          :class => "required" %>
        <span>
        <% if @edit_user.twitter_username.present? %>
          Linked to
          <strong><a href="https://twitter.com/<%= h(@edit_user.twitter_username)
            %>">@<%= h(@edit_user.twitter_username) %></a></strong>
            (<%= link_to "Disconnect", "/settings/twitter_disconnect",
              :method => :post %>)
        <% else %>
          <a href="/settings/twitter_auth">Connect</a>
        <% end %>
        </span>
      </div>
    <% end %>

    <br>

    <div class="legend">
      Security Settings
    </div>

    <div class="boxline">
      <%= f.label :twofa, "Two-Factor Auth:", :class => "required" %>
      <span>
      <% if @edit_user.totp_secret.present? %>
        <span style="color: green; font-weight: bold;">
          Enabled
        </span> (<a href="/settings/2fa">Disable</a>)
      <% else %>
        Disabled (<a href="/settings/2fa">Enroll</a>)
      <% end %>
      </span>
    </div>

    <br>

    <div class="legend">
      Comment Reply Notification Settings
    </div>

    <div class="boxline">
      <%= f.label :email_replies, "Receive E-mail:", :class => "required" %>
      <%= f.check_box :email_replies %>
    </div>

    <div class="boxline">
      <%= f.label :pushover_replies, "Receive Pushover Alert:",
        :class => "required" %>
      <%= f.check_box :pushover_replies %>
      <span class="hint">
        Requires Pushover subscription above
      </span>
    </div>

    <br>

    <div class="legend">
      Comment Mention Notification Settings
    </div>

    <div class="boxline">
      <%= f.label :email_mentions, "Receive E-mail:", :class => "required" %>
      <%= f.check_box :email_mentions %>
    </div>

    <div class="boxline">
      <%= f.label :pushover_mentions, "Receive Pushover Alert:",
        :class => "required" %>
      <%= f.check_box :pushover_mentions %>
      <span class="hint">
        Requires Pushover subscription above
      </span>
    </div>

    <br>

    <div class="legend">
      Private Message Notification Settings
    </div>

    <div class="boxline">
      <%= f.label :email_messages, "Receive E-mail:", :class => "required" %>
      <%= f.check_box :email_messages %>
    </div>

    <div class="boxline">
      <%= f.label :pushover_messages, "Receive Pushover Alert:",
        :class => "required" %>
      <%= f.check_box :pushover_messages %>
      <span class="hint">
        Requires Pushover subscription above
      </span>
    </div>

    <br>

    <div class="legend">
      Submitted Story Comment Settings
    </div>

    <div class="boxline">
      <%= f.label :show_submitted_story_threads,
        raw("Show in <a href=\"/threads\">Your Threads</a>:"),
        :class => "required" %>
      <%= f.check_box :show_submitted_story_threads %>
    </div>

    <br>

    <div class="legend">
      Mailing List Settings
    </div>

    <p>
    When enabled, you will receive all newly submitted stories and comments to
    your e-mail address entered above, except the stories and comments filtered
    by your <a href="/filters">tag filters</a>.
    All e-mail messages will appear to be sent to your private list address
    shown below which you can filter on, and e-mails you send to that address
    will be posted under your account on this website.  You should keep your
    unique list address private to prevent others from posting comments as you.
    </p>

    <div class="boxline">
      <%= f.label :mailing_list_mode, "Receive List E-mails:",
        :class => "required" %>
      <%= f.select :mailing_list_mode, [ [ "No e-mails", 0 ],
        [ "All stories and comments", 1 ], [ "Only stories", 2 ] ] %>
    </div>

    <div class="boxline">
      <label class="required">List Address:</label>
      <span>
      <tt><%= Rails.application.shortname %>-<%=
        @edit_user.mailing_list_token %>@<%= Rails.application.domain %></tt>
      </span>
    </div>

    <br>

    <div class="legend">
      Miscellaneous Settings
    </div>

    <div class="boxline">
      <%= f.label :show_story_previews, "Show Story Previews:",
        :class => "required" %>
      <%= f.check_box :show_story_previews %>
    </div>

    <div class="boxline">
      <%= f.label :show_avatars, "Show User Avatars:", :class => "required" %>
      <%= f.check_box :show_avatars %>
    </div>

    <br>
    <%= f.submit "Save All Settings" %>
  <% end %>

  <br>
  <br>

  <a name="invite"></a>
  <div class="legend">
    Invite a New User
  </div>

  <% if @user.can_invite? %>
    <%= render :partial => "users/invitationform" %>
  <% else %>
      You cannot send invitations: <%= @user.disabled_invite_reason %>
  <% end %>

  <br>
  <br>

  <div class="deletion">
    <%= form_for @edit_user, :url => delete_account_path, :method => :post,
    :html => { :id => "delete_user" } do |f| %>
      <div class="legend">
        Delete Account
      </div>

      <p>
      To permanently delete your account, verify your current password below.
      </p>
      <ul>
        <li>Your account will be put into a deleted state.</li>
        <li>Your username will remain reserved and will not be available to be
          used on any other account.</li>
        <li>Your private messages will be deleted.</li>
        <li>Your submitted stories will not be deleted.</li>
        <li>
          Your comments with negative scores will be deleted, and you can click
          "disown comments" below if you want all of your comments to change to
          list <a href="/u/inactive-user">inactive-user</a> as the author
          instead of your username.
        </li>
      </ul>

      <div class="boxline">
        <%= f.label :password, "Verify Password:", :class => "required" %>
        <%= f.password_field :password, :size => 40, :autocomplete => "off" %>
      </div>
      <div class="boxline">
        <%= f.label :disown, "Disown Comments:" %>
        <%= check_box_tag :disown %>
      </div>

      <br>
      <%= f.submit "Yes, Delete My Account", :class => "deletion" %>
    <% end %>
  </div>
</div>

app/views/settings/twofa.html.erb
<div class="box wide">
  <div class="legend right">
    <a href="/settings">Back to Settings</a>
  </div>
  <div class="legend">
    <%= @title %>
  </div>

  <%= form_for @user, :url => twofa_auth_url, :method => :post do |f| %>
    <p>
    <% if @user.has_2fa? %>
      To turn off two-factor authentication for your account, enter your
      current password:
    <% else %>
      To begin the two-factor authentication enrollment for your account,
      enter your current password:
    <% end %>
    </p>

    <div class="boxline">
      <%= f.label :password, "Current Password:", :class => "required" %>
      <%= f.password_field :password, :size => 40, :autocomplete => "off" %>
    </div>

    <p>
    <% if @user.has_2fa? %>
      <%= submit_tag "Disable Two-Factor Authentication" %>
    <% else %>
      <%= submit_tag "Continue" %>
    <% end %>
  <% end %>
</div>

app/views/settings/twofa_enroll.html.erb
<div class="box wide">
  <div class="legend right">
    <a href="/settings">Back to Settings</a>
  </div>
  <div class="legend">
    <%= @title %>
  </div>

  <p>
  Scan the QR code below or click on it to open in your <a
  href="https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm"
  target="_blank">TOTP</a> application of choice:
  </p>

  <%= raw @qr_svg %>

  <p>
  Once you have finished registering with your TOTP application, proceed to
  the next screen to verify your current TOTP code and actually enable
  Two-Factor Authentication on your account.
  </p>

  <p>
  <%= button_to "Verify and Enable", twofa_verify_url, :method => :get %>
</div>

app/views/settings/twofa_verify.html.erb
<div class="box wide">
  <div class="legend right">
    <a href="/settings">Back to Settings</a>
  </div>
  <div class="legend">
    <%= @title %>
  </div>

  <%= form_tag twofa_update_url do %>
    <p>
    To enable Two-Factor Authentication on your account using your new TOTP
    secret, enter the six-digit code from your TOTP application:
    </p>

    <div class="boxline">
      <%= label_tag :totp_code, "TOTP Code:", :class => "required" %>
      <%= number_field_tag :totp_code, "", :size => 10, :autocomplete => "off",
          :autofocus => true, :class => "totp_code" %>
    </div>

    <p>
    <%= submit_tag "Verify and Enable" %>
  <% end %>
</div>